CREATE TABLE IF NOT EXISTS T_DIVERSIFICATIONIDENTITY_EVENTS_LOGGING
(
EVENT_ID        VARCHAR(64) NOT NULL,
SEARCH_INPUT    VARCHAR(100) NOT NULL,
SEACH_OUTPUT    VARCHAR(500) NOT NULL,
CREATE_DATE     DATE NOT NULL
);
